gem'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rack-flash3'
gem 'bcrypt-ruby'
group :development, :test do
gem 'guard'
gem 'guard-rspec'
gem'guard-cucumber'
gem 'terminal-notifier-guard'
gem 'database_cleaner'
gem 'shotgun'
gem 'cucumber-sinatra'
gem 'capybara'
gem 'cucumber'	
gem 'launchy'
end
